/**
 * Regenerates `src/lib/server/difficulty-ratings.ts`.
 *
 * Project Euler publishes a difficulty rating for every problem that enough people have solved,
 * but only on the full `problem=N` page — `minimal=problems` carries id, title, publication date
 * and solve count and nothing else, and there is no bulk feed for the rating. Scraping a thousand
 * pages is fine to do once by hand; it is not something the app can do while a page load waits,
 * so the ratings are checked in and this script refreshes them.
 *
 *   bun run difficulty:sync
 *
 * Ratings drift by a percent or two as more people solve a problem, and newly published problems
 * are unrated for months, so a refresh every few months is plenty.
 */
import { writeFile } from 'node:fs/promises';
import { parseDifficulty } from '../src/lib/server/difficulty.ts';

const SITE = 'https://projecteuler.net/';
const OUT = new URL('../src/lib/server/difficulty-ratings.ts', import.meta.url);

/** Kept low on purpose: this walks the whole problem set of someone else's site. */
const CONCURRENCY = 6;

async function problemIds(): Promise<number[]> {
	const res = await fetch(`${SITE}minimal=problems`);
	if (!res.ok) throw new Error(`problem list: HTTP ${res.status}`);

	const text = await res.text();
	return text
		.split('\n')
		.slice(1)
		.map((row) => parseInt(row.split('##')[0], 10))
		.filter((id) => !isNaN(id))
		.sort((a, b) => a - b);
}

async function difficultyOf(id: number) {
	const res = await fetch(`${SITE}problem=${id}`);
	if (!res.ok) throw new Error(`problem ${id}: HTTP ${res.status}`);
	return parseDifficulty(await res.text());
}

const ids = await problemIds();
console.error(`fetching difficulty for ${ids.length} problems...`);

const rated: string[] = [];
let unrated = 0;
let failed = 0;

const queue = [...ids];
await Promise.all(
	Array.from({ length: CONCURRENCY }, async () => {
		for (let id = queue.shift(); id !== undefined; id = queue.shift()) {
			try {
				const difficulty = await difficultyOf(id);
				if (difficulty) {
					rated.push(`\t${id}: [${difficulty.level}, ${difficulty.percent}]`);
				} else {
					unrated++;
				}
			} catch (err) {
				// One unreachable page should not cost the other thousand.
				console.error(`  ${id}: ${err}`);
				failed++;
			}
		}
	})
);

// The queue is drained by several workers at once, so the results arrive out of order.
rated.sort((a, b) => parseInt(a, 10) - parseInt(b, 10));

const file = `/**
 * Difficulty ratings scraped from projecteuler.net, as of ${new Date().toISOString().slice(0, 10)}.
 *
 * Generated by \`bun run difficulty:sync\` — do not edit by hand. Problems absent from this table
 * have no published rating yet, which is the normal state for a recently published problem.
 */
export const DIFFICULTY_RATINGS: Record<number, [level: number, percent: number]> = {
${rated.join(',\n')}
};
`;

await writeFile(OUT, file);
console.error(`wrote ${rated.length} ratings (${unrated} unrated, ${failed} failed)`);
